#!/bin/bash
#####################################
#
#	Dice
#
#	For dice games or something
#
#####################################


for (( i=1 ; i<6 ; i++))
do
	let dice[$i]=$RANDOM%6+1
done

if [ "${dice[1]}" = 1 ]
then
	echo
	echo " #########"
	echo "##########"
	echo "  ########"
	echo "  ########"
	echo "  ########"
	echo "  ########"
	echo "  ########"
	echo "  ########"
	echo "  ########"
	echo "############"
	echo 
	
elif [ "${dice[1]}" = 2 ]
then
	echo
	echo "##############"
	echo "##############"
	echo "#####   ######"
	echo "#####   ######"
	echo "       ######"
	echo "      ######"
	echo "     ######"
	echo "   #######"
	echo " ##############"
	echo "###############"
	echo

elif [ "${dice[1]}" = 3 ]
then
	echo
	echo "##############"
	echo "##############"
	echo "#####    #####"
	echo "         #####"
	echo "      ########"
	echo "      ########"
	echo "         #####"
	echo "#####    #####"
	echo "##############"
	echo "##############"
	echo 

elif [ "${dice[1]}" = 4 ]
then
	echo
	echo "#####    #####"
	echo "#####    #####"
	echo "#####    #####"
	echo "#####    #####"
	echo "###############"
	echo "###############"
	echo "         #####"
	echo "         #####"
	echo "         #####"
	echo "         #####"
	echo

elif [ "${dice[1]}" = 5 ]
then
	echo
	echo "##############"
	echo "##############"
	echo "#####    #####"
	echo "#####         "
	echo "#############"
	echo "##############"
	echo "         #####"
	echo "#####    #####"
	echo "##############"
	echo "#############"
	echo

elif [ "${dice[1]}" = 6 ]
then
	echo
	echo "##############"
	echo "##############"
	echo "#####    #####"
	echo "#####         "
	echo "##############"
	echo "##############"
	echo "#####    #####"
	echo "#####    #####"
	echo "##############"
	echo "##############"
	echo

fi

